site_name: SQLStratum
repo_url: https://github.com/aognio/sqlstratum
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Debugging: debugging.md
  - Hydration: hydration.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md
